-- 5 jobs en_US ausentes no D1 (Untitled-2)
-- Fonte: farra.sql legacy enUS
-- Idempotente: INSERT OR IGNORE + UPDATE order via migrate-jobs-order-en-us.sql

-- PÍLULA DE FARINHA - O ESCÂNDALO QUE GEROU VIDAS (45ad7fe9-2705-4502-aadb-0820964e9d48) locale=en_US
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "pilula de farinha.png", 'attachment-jobs-pilula-de-farinha-o-escandalo-que-gerou-vidas-en-us', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"pilula de farinha.png","attachment_path":"https://bucket.farra.media/pilula de farinha.png","attachment_alt":"PÍLULA DE FARINHA - O ESCÂNDALO QUE GEROU VIDAS"}', 1776363971808, 1776363971808
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-pilula-de-farinha-o-escandalo-que-gerou-vidas-en-us');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1), 'PÍLULA DE FARINHA - O ESCÂNDALO QUE GEROU VIDAS', 'pilula-de-farinha-o-escandalo-que-gerou-vidas-en-us', '', 'A co-production of Farra and Warner Bros., this three-episode documentary series recounts the 1998 scandal when tons of placebo of Brazil''s best-selling contraceptive reached pharmacies, resulting in hundreds of unwanted pregnancies. A story that blends drama, police investigation, and the pursuit of justice, created by Jana Medeiros and Heddy Fernandes, with general direction by Cassia Dian and executive production by Verônica Villa and Gui Vieira.', 'published', '{"videos":"https://vimeo.com/1148044414","videosHome":null,"videosHomeOrder":null,"order":122,"fichaTecnica":[],"language":"enUS","socialMedia":null,"reel":null,"posttype":"jobs","legacy_id":"45ad7fe9-2705-4502-aadb-0820964e9d48","legacy_posttype":"jobs","slug":"pilula-de-farinha-o-escandalo-que-gerou-vidas","image":"https://bucket.farra.media/pilula de farinha.png"}', 1773848886000, 1773848886000, 1776363971808
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='pilula-de-farinha-o-escandalo-que-gerou-vidas-en-us');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='pilula-de-farinha-o-escandalo-que-gerou-vidas-en-us' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-pilula-de-farinha-o-escandalo-que-gerou-vidas-en-us' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='pilula-de-farinha-o-escandalo-que-gerou-vidas-en-us') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-pilula-de-farinha-o-escandalo-que-gerou-vidas-en-us');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-pilula-de-farinha-o-escandalo-que-gerou-vidas-en-us' LIMIT 1)) WHERE slug='pilula-de-farinha-o-escandalo-que-gerou-vidas-en-us';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1) WHERE slug='pilula-de-farinha-o-escandalo-que-gerou-vidas-en-us' AND id_locale_code IS NULL;
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='pilula-de-farinha-o-escandalo-que-gerou-vidas-en-us' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='tv-and-streaming-en-us' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='pilula-de-farinha-o-escandalo-que-gerou-vidas-en-us') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='tv-and-streaming-en-us' AND type='categorias');

-- ABERTO AO PÚBLICO | GLOBO (1127dd74-c91d-40d0-aba1-d5dc696a139a) locale=en_US
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "Featured_Image_Site Farra.png", 'attachment-jobs-aberto-ao-publico-globo-en-us', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"Featured_Image_Site Farra.png","attachment_path":"https://bucket.farra.media/Featured_Image_Site Farra.png","attachment_alt":"ABERTO AO PÚBLICO | GLOBO"}', 1773850559934, 1773850559934
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-aberto-ao-publico-globo-en-us');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1), 'ABERTO AO PÚBLICO | GLOBO', 'aberto-ao-publico-globo-en-us', '', 'The audience of anonymous people as the main protagonists of a TV program featuring comedians and celebrities. It was with this purpose that Farra, in co-production with Dromedário, developed, produced, and post-produced two seasons of "Aberto ao Público," a Globo comedy show that mixes comedy with a generous dose of unpretentiousness, irreverence, and embarrassing sincerity, in a completely unpredictable program. In addition to the episodes of this original format, we also produced extra promotional pieces and vertical micro-content that flooded the social media of Globo, the comedians, and Globo guests, showing behind-the-scenes footage, bloopers, and gems that only happen when you put together a stage, an audience, and comedians loose with a microphone.', 'published', '{"videos":["https://vimeo.com/1162256512","https://vimeo.com/1162268067?fl=tl&fe=ec"],"videosHome":null,"videosHomeOrder":null,"order":122,"fichaTecnica":[],"language":"enUS","socialMedia":null,"reel":null,"posttype":"jobs","legacy_id":"1127dd74-c91d-40d0-aba1-d5dc696a139a","legacy_posttype":"jobs","slug":"aberto-ao-publico-globo","image":"https://bucket.farra.media/Featured_Image_Site Farra.png"}', 1773850180000, 1773850180000, 1773850559934
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='aberto-ao-publico-globo-en-us');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='aberto-ao-publico-globo-en-us' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-aberto-ao-publico-globo-en-us' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='aberto-ao-publico-globo-en-us') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-aberto-ao-publico-globo-en-us');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-aberto-ao-publico-globo-en-us' LIMIT 1)) WHERE slug='aberto-ao-publico-globo-en-us';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1) WHERE slug='aberto-ao-publico-globo-en-us' AND id_locale_code IS NULL;
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='aberto-ao-publico-globo-en-us' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='tv-and-streaming-en-us' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='aberto-ao-publico-globo-en-us') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='tv-and-streaming-en-us' AND type='categorias');

-- No Ritmo da Lore (be1aa998-8848-420c-ab2d-3ba5fdf70ea1) locale=en_US
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "lore improta.png", 'attachment-jobs-no-ritmo-da-lore-en-us', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"lore improta.png","attachment_path":"https://bucket.farra.media/lore improta.png","attachment_alt":"No Ritmo da Lore"}', 1776364153373, 1776364153373
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-no-ritmo-da-lore-en-us');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1), 'No Ritmo da Lore', 'no-ritmo-da-lore-en-us', '', 'Produced by FARRA, with script and direction by Andre Brandt, this web series shows the behind-the-scenes of the Viradouro muse, Lore Improta''s, carnival. Over 6 episodes, we''ll follow her outfit selection, filming days, dance classes, rehearsals at the samba school''s headquarters, street rehearsals, and everything else that happens non-stop. Don''t miss it, a new episode every Thursday on YouTube.\r\n', 'published', '{"videos":"https://vimeo.com/1057547400","videosHome":null,"videosHomeOrder":null,"order":121,"fichaTecnica":[{"title":"Direction e Writer:","content":"André Brandt"},{"title":"Production:","content":"Farra"},{"title":"Executive Producer:","content":"Gui Vieira e Tayna Adam"},{"title":"Production Management:","content":"Juliana Hodas"},{"title":"Executive Production Assistance:","content":" Beatriz Fontana Carvalho"},{"title":"Financer:","content":" Andressa Carrijo"},{"title":"Design:","content":"Beatriz Vidal"},{"title":"","content":""},{"title":"Motion Design:","content":"Serginho Dimi"},{"title":"Cinematography: ","content":"Alex Tavares"},{"title":"Filmmaker Rio de Janeiro: ","content":"Miguel Souza"},{"title":"Filmmaker Salvador: ","content":"Tarcisio Sampaio"},{"title":"Edition: ","content":"Mike Lopes Prado"},{"title":"Post-production coordination: ","content":"Frederico Kesselring"},{"title":"Filmmaker São Paulo: ","content":"Victor Lima"},{"title":"Audio Production: ","content":"DreamBox"},{"title":"Color: ","content":"Gabriel Ranzani"}],"language":"enUS","socialMedia":null,"reel":null,"posttype":"jobs","legacy_id":"be1aa998-8848-420c-ab2d-3ba5fdf70ea1","legacy_posttype":"jobs","slug":"no-ritmo-da-lore","image":"https://bucket.farra.media/lore improta.png"}', 1739790091000, 1739790091000, 1776364153373
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='no-ritmo-da-lore-en-us');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='no-ritmo-da-lore-en-us' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-no-ritmo-da-lore-en-us' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='no-ritmo-da-lore-en-us') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-no-ritmo-da-lore-en-us');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-no-ritmo-da-lore-en-us' LIMIT 1)) WHERE slug='no-ritmo-da-lore-en-us';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1) WHERE slug='no-ritmo-da-lore-en-us' AND id_locale_code IS NULL;
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='no-ritmo-da-lore-en-us' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='branded-entertainment-en-us' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='no-ritmo-da-lore-en-us') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='branded-entertainment-en-us' AND type='categorias');

-- RAFI (9494ce47-96a4-4cc4-9a64-d004acb0b177) locale=en_US
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "RAFI.png", 'attachment-jobs-rafi-en-us', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"RAFI.png","attachment_path":"https://bucket.farra.media/RAFI.png","attachment_alt":"RAFI"}', 1776169449853, 1776169449853
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-rafi-en-us');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1), 'RAFI', 'rafi-en-us', '', 'After six years carving out his place in one of the most competitive stand-up comedy scenes in the world, Rafinha Bastos is preparing to record his first English-language special. This exclusive documentary offers a unique behind-the-scenes look at the three days leading up to the recording, following the comedian through his routine at comedy clubs across the US, while he reflects on his journey—from Brazil to the long-awaited international recognition.', 'published', '{"videos":"https://vimeo.com/1047243492","videosHome":null,"videosHomeOrder":null,"order":120,"fichaTecnica":[{"title":"Production:","content":"Farra"},{"title":"General Direction and Screenplay","content":"André Brandt"},{"title":"Digital Art: ","content":"Beatriz Vidal"},{"title":"Producers:","content":" Gui Vieira, Gui Cintra, André Brandt"},{"title":"Cinematography:","content":"Alex Tavares"},{"title":"Executive Producer:","content":"Gui Vieira e Tayna Adam"},{"title":"Assistente Producer:","content":"Beatriz Fontada"},{"title":"Producer:","content":"Juliana Hodas"},{"title":"Post-production Coordination: ","content":"Fred Kesselring"},{"title":"Edition:","content":"Dreiky F."},{"title":"Financer:","content":"Andressa Carrijo"},{"title":"Edition Assistent:","content":"Mike Prado"},{"title":"Color:","content":"Gabriel Ranzani"},{"title":"Sound Producer:","content":" Dream Box Produções LTDA "},{"title":"Sound Editing and Mixing:","content":"Guilherme Picolo e Tullio Zarpao"},{"title":"Completion: ","content":"Fred Kesselring e Dreiky F."},{"title":"Subtitles: ","content":"Dreiky Fraga"},{"title":"Executive Producer of Post-Sound","content":"Daniel Picolo "}],"language":"enUS","socialMedia":null,"reel":null,"posttype":"jobs","legacy_id":"9494ce47-96a4-4cc4-9a64-d004acb0b177","legacy_posttype":"jobs","slug":"rafi","image":"https://bucket.farra.media/RAFI.png"}', 1773863323000, 1773863323000, 1776169449853
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='rafi-en-us');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='rafi-en-us' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-rafi-en-us' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='rafi-en-us') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-rafi-en-us');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-rafi-en-us' LIMIT 1)) WHERE slug='rafi-en-us';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1) WHERE slug='rafi-en-us' AND id_locale_code IS NULL;
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='rafi-en-us' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='tv-and-streaming-en-us' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='rafi-en-us') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='tv-and-streaming-en-us' AND type='categorias');

-- CONTROLE DE QUALIDADE com REGINA VOLPATO | PARAMOUNT + (88db2fa3-fb7a-4ef6-8aaf-d44b1a3fcb87) locale=en_US
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "REGUN.png", 'attachment-jobs-controle-de-qualidade-com-regina-volpato-paramount-en-us', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"REGUN.png","attachment_path":"https://bucket.farra.media/REGUN.png","attachment_alt":"CONTROLE DE QUALIDADE com REGINA VOLPATO | PARAMOUNT +"}', 1776364316015, 1776364316015
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-controle-de-qualidade-com-regina-volpato-paramount-en-us');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1), 'CONTROLE DE QUALIDADE com REGINA VOLPATO | PARAMOUNT +', 'controle-de-qualidade-com-regina-volpato-paramount-en-us', '', 'Farra created and produced a new campaign for Paramount+, starring Regina Volpato, with the aim of promoting the streaming service''s drama series – without neglecting the good humor that is a characteristic of the Brazilian people. Directed by Gui Cintra and following the concept "Addicted to a good drama," the proposal is to highlight that the platform has become a benchmark when it comes to offering a strong catalog of the genre to the Brazilian audience, which, like Paramount+, is passionate about a good drama.', 'published', '{"videos":"https://vimeo.com/1068297412","videosHome":null,"videosHomeOrder":null,"order":120,"fichaTecnica":[{"title":"Production:","content":"Farra"},{"title":"Direction: ","content":"Gui Cintra"}],"language":"enUS","socialMedia":null,"reel":null,"posttype":"jobs","legacy_id":"88db2fa3-fb7a-4ef6-8aaf-d44b1a3fcb87","legacy_posttype":"jobs","slug":"controle-de-qualidade-com-regina-volpato-paramount","image":"https://bucket.farra.media/REGUN.png"}', 1776364254000, 1776364254000, 1776364316015
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='controle-de-qualidade-com-regina-volpato-paramount-en-us');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='controle-de-qualidade-com-regina-volpato-paramount-en-us' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-controle-de-qualidade-com-regina-volpato-paramount-en-us' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='controle-de-qualidade-com-regina-volpato-paramount-en-us') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-controle-de-qualidade-com-regina-volpato-paramount-en-us');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-controle-de-qualidade-com-regina-volpato-paramount-en-us' LIMIT 1)) WHERE slug='controle-de-qualidade-com-regina-volpato-paramount-en-us';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1) WHERE slug='controle-de-qualidade-com-regina-volpato-paramount-en-us' AND id_locale_code IS NULL;
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='controle-de-qualidade-com-regina-volpato-paramount-en-us' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='advertising-en-us' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='controle-de-qualidade-com-regina-volpato-paramount-en-us') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='advertising-en-us' AND type='categorias');
