-- Jobs faltantes (SonicJS -> EdgePress)
-- Fonte: farra.sql / Untitled-3
-- Idempotente: pode rodar mais de uma vez
-- Pré-requisito: migrate-jobs.sql (post type, taxonomias, locales)

-- DevDay Exchange | OPEN AI (8642631f-3aa6-4dc1-a3c3-1807902bf57f) locale=pt_BR
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "SITE.png", 'attachment-jobs-devday-exchange-open-ai-pt-br', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"SITE.png","attachment_path":"https://bucket.farra.media/SITE.png","attachment_alt":"DevDay Exchange | OPEN AI"}', 1767706545000, 1776366356517
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-devday-exchange-open-ai-pt-br');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='pt_BR' LIMIT 1), 'DEVDAY EXCHANGE | OPEN AI', 'devday-exchange-open-ai-pt-br', '', 'Com produção da Farra, o encontro internacional reuniu desenvolvedores, líderes de tecnologia e criadores em um dia dedicado à inovação e às possibilidades da inteligência artificial. Da ambientação à experiência dos convidados, a Farra assinou toda a produção, criando um espaço de troca, aprendizado e conexão entre as comunidades de tecnologia.', 'published', '{"videos":"https://vimeo.com/1148055555","videosHome":null,"videosHomeOrder":null,"order":110,"fichaTecnica":[],"language":"ptbr","socialMedia":null,"reel":null,"posttype":"jobs","slug":"devday-exchange-open-ai","image":"https://bucket.farra.media/SITE.png","legacy_id":"8642631f-3aa6-4dc1-a3c3-1807902bf57f","legacy_posttype":"jobs"}', 1767706545000, 1767706545000, 1776366356517
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='devday-exchange-open-ai-pt-br');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='devday-exchange-open-ai-pt-br' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-devday-exchange-open-ai-pt-br' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='devday-exchange-open-ai-pt-br') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-devday-exchange-open-ai-pt-br');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-devday-exchange-open-ai-pt-br' LIMIT 1)) WHERE slug='devday-exchange-open-ai-pt-br';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='pt_BR' LIMIT 1) WHERE slug='devday-exchange-open-ai-pt-br' AND id_locale_code IS NULL;

-- Dias das Mães Dudalina com Maria Fernanda Cândido (27802662-4152-45ce-93a6-7dbf57f56a48) locale=pt_BR
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "dudalina dia das maes.png", 'attachment-jobs-dias-das-maes-dudalina-com-maria-fernanda-candido-pt-br', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"dudalina dia das maes.png","attachment_path":"https://bucket.farra.media/dudalina dia das maes.png","attachment_alt":"Dias das Mães Dudalina com Maria Fernanda Cândido"}', 1767720699000, 1769535492819
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-dias-das-maes-dudalina-com-maria-fernanda-candido-pt-br');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='pt_BR' LIMIT 1), 'Dias das Mães Dudalina com Maria Fernanda Cândido', 'dias-das-maes-dudalina-com-maria-fernanda-candido-pt-br', '', 'Em parceria com Dudalina, marca que a Farra já criou, dirigiu e produziu muitas campanhas, a Farra criou uma lidna campanha publicitária para o dia das mães, estrelando Maria Fernanda Cândido. Dirigido por Hugo Moura e produzido pela Farra. ', 'published', '{"videos":"https://vimeo.com/1098302937","videosHome":null,"videosHomeOrder":null,"order":101,"fichaTecnica":[{"title":"Produção:","content":"Farra"},{"title":"Direção:","content":"Hugo Moura"}],"language":"ptbr","socialMedia":null,"reel":null,"posttype":"jobs","slug":"dias-das-maes-dudalina-com-maria-fernanda-candido","image":"https://bucket.farra.media/dudalina dia das maes.png","legacy_id":"27802662-4152-45ce-93a6-7dbf57f56a48","legacy_posttype":"jobs"}', 1767720699000, 1767720699000, 1769535492819
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='dias-das-maes-dudalina-com-maria-fernanda-candido-pt-br');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='dias-das-maes-dudalina-com-maria-fernanda-candido-pt-br' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-dias-das-maes-dudalina-com-maria-fernanda-candido-pt-br' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='dias-das-maes-dudalina-com-maria-fernanda-candido-pt-br') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-dias-das-maes-dudalina-com-maria-fernanda-candido-pt-br');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-dias-das-maes-dudalina-com-maria-fernanda-candido-pt-br' LIMIT 1)) WHERE slug='dias-das-maes-dudalina-com-maria-fernanda-candido-pt-br';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='pt_BR' LIMIT 1) WHERE slug='dias-das-maes-dudalina-com-maria-fernanda-candido-pt-br' AND id_locale_code IS NULL;

-- CAMPANHA DIGITAL - PÍLULA DE FARINHA | HBO MAX (84e086ed-0d51-41d0-b25e-770beb3a1327) locale=pt_BR
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "pilula 2.png", 'attachment-jobs-campanha-digital-pilula-de-farinha-hbo-max-pt-br', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"pilula 2.png","attachment_path":"https://bucket.farra.media/pilula 2.png","attachment_alt":"CAMPANHA DIGITAL - PÍLULA DE FARINHA | HBO MAX"}', 1776276568000, 1776365664761
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-campanha-digital-pilula-de-farinha-hbo-max-pt-br');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='pt_BR' LIMIT 1), 'CAMPANHA DIGITAL - PÍLULA DE FARINHA | HBO MAX', 'campanha-digital-pilula-de-farinha-hbo-max-pt-br', '', 'Para a divulgação da série, a Farra desenvolveu conteúdos a partir de entrevistas com a diretora Cássia Dian e a co-criadora Jana Medeiros.

Os materiais foram estruturados como promos conectadas a cada episódio, expandindo a narrativa da docussérie nas redes sociais e reforçando o interesse do público ao longo da exibição.', 'published', '{"videos":"https://vimeo.com/1183769207","videosHome":null,"videosHomeOrder":null,"order":102,"fichaTecnica":[{"title":"Produção:","content":"FARRA"},{"title":"Social Media Manager:","content":"Patricia Vergili "}],"language":"ptbr","socialMedia":null,"reel":null,"posttype":"jobs","slug":"campanha-digital-pilula-de-farinha-hbo-max","image":"https://bucket.farra.media/pilula 2.png","legacy_id":"84e086ed-0d51-41d0-b25e-770beb3a1327","legacy_posttype":"jobs"}', 1776276568000, 1776276568000, 1776365664761
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='campanha-digital-pilula-de-farinha-hbo-max-pt-br');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='campanha-digital-pilula-de-farinha-hbo-max-pt-br' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-campanha-digital-pilula-de-farinha-hbo-max-pt-br' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='campanha-digital-pilula-de-farinha-hbo-max-pt-br') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-campanha-digital-pilula-de-farinha-hbo-max-pt-br');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-campanha-digital-pilula-de-farinha-hbo-max-pt-br' LIMIT 1)) WHERE slug='campanha-digital-pilula-de-farinha-hbo-max-pt-br';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='pt_BR' LIMIT 1) WHERE slug='campanha-digital-pilula-de-farinha-hbo-max-pt-br' AND id_locale_code IS NULL;

-- Organização Pura - Novela Vertical | BV Financeira (a4f72d12-0953-47c4-aaad-12a71771441f) locale=pt_BR
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "bv financeira.png", 'attachment-jobs-organizacao-pura-novela-vertical-bv-financeira-pt-br', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"bv financeira.png","attachment_path":"https://bucket.farra.media/bv financeira.png","attachment_alt":"Organização Pura - Novela Vertical | BV Financeira"}', 1776956504654, 1776956504654
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-organizacao-pura-novela-vertical-bv-financeira-pt-br');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='pt_BR' LIMIT 1), 'Organização Pura - Novela Vertical | BV Financeira', 'organizacao-pura-novela-vertical-bv-financeira-pt-br', '', 'A Farra foi responsável pela pós-produção de "Organização Pura", novelinha vertical do banco BV, feita em parceria com a Play9 Content Group.
', 'published', '{"videos":"https://vimeo.com/1185909737","videosHome":null,"videosHomeOrder":null,"order":108,"fichaTecnica":[{"title":"Produção:","content":"Farra"},{"title":"Coordenadora de pós","content":"Lais Paixão"},{"title":"Assistente de pós","content":"Carol Pessoa"},{"title":"Editora e motion ","content":"Thais Maranhão"},{"title":"Editor social","content":"Mike Prado"},{"title":"Editor","content":"Luís Guilherme Chagas"},{"title":"Finalizador","content":"Fred Kesselring"},{"title":"Motion","content":"Serginho Dimi"},{"title":"Cor","content":"Ranza"},{"title":"Mixagem","content":"Dreambox"},{"title":"Produção executiva","content":"Guilherme Vieira"},{"title":"Assistente de Produção Executiva","content":"Victoria Rodriguez "}],"language":"ptbr","socialMedia":null,"reel":null,"posttype":"jobs","slug":"organizacao-pura-novela-vertical-bv-financeira","image":"https://bucket.farra.media/bv financeira.png","legacy_id":"a4f72d12-0953-47c4-aaad-12a71771441f","legacy_posttype":"jobs"}', 1776956504654, 1776956504654, 1776956504654
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='organizacao-pura-novela-vertical-bv-financeira-pt-br');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='organizacao-pura-novela-vertical-bv-financeira-pt-br' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-organizacao-pura-novela-vertical-bv-financeira-pt-br' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='organizacao-pura-novela-vertical-bv-financeira-pt-br') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-organizacao-pura-novela-vertical-bv-financeira-pt-br');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-organizacao-pura-novela-vertical-bv-financeira-pt-br' LIMIT 1)) WHERE slug='organizacao-pura-novela-vertical-bv-financeira-pt-br';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='pt_BR' LIMIT 1) WHERE slug='organizacao-pura-novela-vertical-bv-financeira-pt-br' AND id_locale_code IS NULL;

-- CAMPANHA DIGITAL: ABERTO AO PÚBLICO Temporada 1 e 2 | TVGlobo (21b84261-3a99-4644-9cfd-0f7cbc998790) locale=pt_BR
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "aberto ao publico.png", 'attachment-jobs-campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo-pt-br', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"aberto ao publico.png","attachment_path":"https://bucket.farra.media/aberto ao publico.png","attachment_alt":"CAMPANHA DIGITAL: ABERTO AO PÚBLICO Temporada 1 e 2 | TVGlobo"}', 1776364402805, 1776364402805
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo-pt-br');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='pt_BR' LIMIT 1), 'CAMPANHA DIGITAL: ABERTO AO PÚBLICO Temporada 1 e 2 | TVGlobo', 'campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo-pt-br', '', 'Para as duas temporadas do programa, a Farra desenvolveu uma estratégia robusta de conteúdo para redes sociais, com 169 peças digitais.
Os desdobramentos incluíram conteúdos por episódio, trends com convidados, promos, cortes verticais legendados, carrosséis de frases e memes, compilados de melhores momentos, além de extras, bastidores e materiais de pré-estreia. Um volume consistente de conteúdo que ajudou a manter o programa presente nas redes durante toda a temporada.', 'published', '{"videos":["https://vimeo.com/1183770621","https://vimeo.com/1183769773"],"videosHome":null,"videosHomeOrder":null,"order":94,"fichaTecnica":[{"title":"Produção:","content":"Farra"},{"title":"Social Media Manager: ","content":"Patrícia Vergili"}],"language":"ptbr","socialMedia":null,"reel":null,"posttype":"jobs","slug":"campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo","image":"https://bucket.farra.media/aberto ao publico.png","legacy_id":"21b84261-3a99-4644-9cfd-0f7cbc998790","legacy_posttype":"jobs"}', 1776364402805, 1776364402805, 1776364402805
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo-pt-br');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo-pt-br' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo-pt-br' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo-pt-br') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo-pt-br');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo-pt-br' LIMIT 1)) WHERE slug='campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo-pt-br';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='pt_BR' LIMIT 1) WHERE slug='campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo-pt-br' AND id_locale_code IS NULL;

-- DevDay Exchange | OPEN AI (b664fb6d-169c-499c-a2b0-9a3898171771) locale=en_US
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "SITE.png", 'attachment-jobs-devday-exchange-open-ai-en-us', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"SITE.png","attachment_path":"https://bucket.farra.media/SITE.png","attachment_alt":"DevDay Exchange | OPEN AI"}', 1773853239000, 1776366395746
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-devday-exchange-open-ai-en-us');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1), 'DevDay Exchange | OPEN AI', 'devday-exchange-open-ai-en-us', '', 'Produced by Farra, the international event brought together developers, technology leaders, and creators for a day dedicated to innovation and the possibilities of artificial intelligence. From the ambiance to the guest experience, Farra handled all aspects of the production, creating a space for exchange, learning, and connection among technology communities.', 'published', '{"videos":"https://vimeo.com/1148055555","videosHome":null,"videosHomeOrder":null,"order":121,"fichaTecnica":[],"language":"enUS","socialMedia":null,"reel":null,"posttype":"jobs","slug":"devday-exchange-open-ai","image":"https://bucket.farra.media/SITE.png","legacy_id":"b664fb6d-169c-499c-a2b0-9a3898171771","legacy_posttype":"jobs"}', 1773853239000, 1773853239000, 1776366395746
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='devday-exchange-open-ai-en-us');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='devday-exchange-open-ai-en-us' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-devday-exchange-open-ai-en-us' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='devday-exchange-open-ai-en-us') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-devday-exchange-open-ai-en-us');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-devday-exchange-open-ai-en-us' LIMIT 1)) WHERE slug='devday-exchange-open-ai-en-us';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1) WHERE slug='devday-exchange-open-ai-en-us' AND id_locale_code IS NULL;

-- DIGITAL CAMPAIGN - PÍLULA DE FARINHA | HBO MAX (239f7b71-7d3e-4bc1-b629-5d8956706b30) locale=en_US
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "pilula 2.png", 'attachment-jobs-digital-campaign-pilula-de-farinha-hbo-max-en-us', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"pilula 2.png","attachment_path":"https://bucket.farra.media/pilula 2.png","attachment_alt":"DIGITAL CAMPAIGN - PÍLULA DE FARINHA | HBO MAX"}', 1776364196000, 1776365693047
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-digital-campaign-pilula-de-farinha-hbo-max-en-us');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1), 'DIGITAL CAMPAIGN - PÍLULA DE FARINHA | HBO MAX', 'digital-campaign-pilula-de-farinha-hbo-max-en-us', '', 'To promote the series, Farra developed content based on interviews with director Cássia Dian and co-creator Jana Medeiros.

The materials were structured as promos connected to each episode, expanding the docuseries'' narrative on social media and reinforcing audience interest throughout the broadcast.', 'published', '{"videos":"https://vimeo.com/1183769207","videosHome":null,"videosHomeOrder":null,"order":120,"fichaTecnica":[{"title":"Production:","content":"FARRA"},{"title":"Social Media Manager:","content":"Patricia Vergili "}],"language":"enUS","socialMedia":null,"reel":null,"posttype":"jobs","slug":"digital-campaign-pilula-de-farinha-hbo-max","image":"https://bucket.farra.media/pilula 2.png","legacy_id":"239f7b71-7d3e-4bc1-b629-5d8956706b30","legacy_posttype":"jobs"}', 1776364196000, 1776364196000, 1776365693047
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='digital-campaign-pilula-de-farinha-hbo-max-en-us');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='digital-campaign-pilula-de-farinha-hbo-max-en-us' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-digital-campaign-pilula-de-farinha-hbo-max-en-us' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='digital-campaign-pilula-de-farinha-hbo-max-en-us') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-digital-campaign-pilula-de-farinha-hbo-max-en-us');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-digital-campaign-pilula-de-farinha-hbo-max-en-us' LIMIT 1)) WHERE slug='digital-campaign-pilula-de-farinha-hbo-max-en-us';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1) WHERE slug='digital-campaign-pilula-de-farinha-hbo-max-en-us' AND id_locale_code IS NULL;

-- Organização Pura -  Vertical Novel | BV Financeira (bad02a00-eea1-4df9-a111-70deea7b451a) locale=en_US
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "bv financeira.png", 'attachment-jobs-organizacao-pura-vertical-novel-bv-financeira-en-us', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"bv financeira.png","attachment_path":"https://bucket.farra.media/bv financeira.png","attachment_alt":"Organização Pura -  Vertical Novel | BV Financeira"}', 1776869710000, 1776956738889
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-organizacao-pura-vertical-novel-bv-financeira-en-us');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1), 'Organização Pura -  Vertical Novel | BV Financeira', 'organizacao-pura-vertical-novel-bv-financeira-en-us', '', 'Farra was responsible for the post-production of "Organização Pura," a vertical soap opera for Banco BV, made in partnership with Play9 Content Group. ', 'published', '{"videos":"https://vimeo.com/1185909737","videosHome":null,"videosHomeOrder":null,"order":121,"fichaTecnica":[{"title":"Production:","content":"Farra"},{"title":"Pos-production Coordinator ","content":"Lais Paixão"},{"title":"Pos-production Assistant ","content":"Carol Pessoa"},{"title":"Editor and motion ","content":"Thais Maranhão"},{"title":"Social Editor","content":"Mike Prado"},{"title":"Editor","content":"Luís Guilherme Chagas"},{"title":"Finalizador","content":"Fred Kesselring"},{"title":"Motion","content":"Serginho Dimi"},{"title":"Color","content":"Ranza"},{"title":"Mixer","content":"Dreambox"},{"title":"Executive Producer","content":"Guilherme Vieira"},{"title":"Executive Production Assistant","content":"Victoria Rodriguez "}],"language":"enUS","socialMedia":null,"reel":null,"posttype":"jobs","slug":"organizacao-pura-vertical-novel-bv-financeira","image":"https://bucket.farra.media/bv financeira.png","legacy_id":"bad02a00-eea1-4df9-a111-70deea7b451a","legacy_posttype":"jobs"}', 1776869710000, 1776869710000, 1776956738889
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='organizacao-pura-vertical-novel-bv-financeira-en-us');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='organizacao-pura-vertical-novel-bv-financeira-en-us' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-organizacao-pura-vertical-novel-bv-financeira-en-us' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='organizacao-pura-vertical-novel-bv-financeira-en-us') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-organizacao-pura-vertical-novel-bv-financeira-en-us');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-organizacao-pura-vertical-novel-bv-financeira-en-us' LIMIT 1)) WHERE slug='organizacao-pura-vertical-novel-bv-financeira-en-us';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1) WHERE slug='organizacao-pura-vertical-novel-bv-financeira-en-us' AND id_locale_code IS NULL;

-- DIGITAL CAMPAIGN: ABERTO AO PÚBLICO Temporada 1 e 2 | TVGlobo (2538e6d6-6776-455c-bb9f-b98da2de9d57) locale=en_US
INSERT OR IGNORE INTO edp_posts (post_type_id, title, slug, status, meta_values, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='attachment' LIMIT 1), "aberto ao publico.png", 'attachment-jobs-digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo-en-us', 'published', '{"show_in_menu":false,"menu_options":[],"icon":"line-md:file","mime_type":"image/png","attachment_file":"aberto ao publico.png","attachment_path":"https://bucket.farra.media/aberto ao publico.png","attachment_alt":"DIGITAL CAMPAIGN: ABERTO AO PÚBLICO Temporada 1 e 2 | TVGlobo"}', 1776363212000, 1776364449449
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo-en-us');
INSERT OR IGNORE INTO edp_posts (post_type_id, id_locale_code, title, slug, excerpt, body, status, meta_values, published_at, created_at, updated_at)
SELECT (SELECT id FROM edp_post_types WHERE slug='jobs' LIMIT 1), (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1), 'DIGITAL CAMPAIGN: ABERTO AO PÚBLICO Temporada 1 e 2 | TVGlobo', 'digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo-en-us', '', 'For the show''s two seasons, Farra developed a robust social media content strategy, with 169 digital pieces.

The developments included episode-specific content, trending topics with guests, promos, subtitled vertical cuts, carousels of quotes and memes, compilations of best moments, as well as extras, behind-the-scenes footage, and pre-premiere materials. A consistent volume of content that helped keep the show present on social media throughout the season.', 'published', '{"videos":["https://vimeo.com/1183770621","https://vimeo.com/1183769773"],"videosHome":null,"videosHomeOrder":null,"order":116,"fichaTecnica":[{"title":"Production:","content":"Farra"},{"title":"Social Media Manager: ","content":"Patrícia Vergili"}],"language":"enUS","socialMedia":null,"reel":null,"posttype":"jobs","slug":"digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo","image":"https://bucket.farra.media/aberto ao publico.png","legacy_id":"2538e6d6-6776-455c-bb9f-b98da2de9d57","legacy_posttype":"jobs"}', 1776363212000, 1776363212000, 1776364449449
WHERE NOT EXISTS (SELECT 1 FROM edp_posts WHERE slug='digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo-en-us');
INSERT OR IGNORE INTO edp_posts_media (post_id, media_id)
SELECT (SELECT id FROM edp_posts WHERE slug='digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo-en-us' LIMIT 1), (SELECT id FROM edp_posts WHERE slug='attachment-jobs-digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo-en-us' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo-en-us') AND EXISTS (SELECT 1 FROM edp_posts WHERE slug='attachment-jobs-digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo-en-us');
UPDATE edp_posts SET meta_values = json_set(meta_values, '$.post_thumbnail_id', (SELECT CAST(id AS TEXT) FROM edp_posts WHERE slug='attachment-jobs-digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo-en-us' LIMIT 1)) WHERE slug='digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo-en-us';
UPDATE edp_posts SET id_locale_code = (SELECT id FROM edp_locales WHERE locale_code='en_US' LIMIT 1) WHERE slug='digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo-en-us' AND id_locale_code IS NULL;

INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='devday-exchange-open-ai-pt-br' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='corporativo-pt-br' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='devday-exchange-open-ai-pt-br') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='corporativo-pt-br' AND type='categorias');
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='devday-exchange-open-ai-pt-br' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='lives-e-eventos-pt-br' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='devday-exchange-open-ai-pt-br') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='lives-e-eventos-pt-br' AND type='categorias');
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='dias-das-maes-dudalina-com-maria-fernanda-candido-pt-br' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='branded-entertainment-pt-br' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='dias-das-maes-dudalina-com-maria-fernanda-candido-pt-br') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='branded-entertainment-pt-br' AND type='categorias');
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='campanha-digital-pilula-de-farinha-hbo-max-pt-br' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='social-media-pt-br' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='campanha-digital-pilula-de-farinha-hbo-max-pt-br') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='social-media-pt-br' AND type='categorias');
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='organizacao-pura-novela-vertical-bv-financeira-pt-br' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='social-media-pt-br' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='organizacao-pura-novela-vertical-bv-financeira-pt-br') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='social-media-pt-br' AND type='categorias');
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo-pt-br' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='social-media-pt-br' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='campanha-digital-aberto-ao-publico-temporada-1-e-2-tvglobo-pt-br') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='social-media-pt-br' AND type='categorias');
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='devday-exchange-open-ai-en-us' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='corporate-en-us' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='devday-exchange-open-ai-en-us') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='corporate-en-us' AND type='categorias');
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='devday-exchange-open-ai-en-us' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='livestreams-and-events-en-us' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='devday-exchange-open-ai-en-us') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='livestreams-and-events-en-us' AND type='categorias');
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='digital-campaign-pilula-de-farinha-hbo-max-en-us' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='social-media-en-us' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='digital-campaign-pilula-de-farinha-hbo-max-en-us') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='social-media-en-us' AND type='categorias');
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='organizacao-pura-vertical-novel-bv-financeira-en-us' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='social-media-en-us' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='organizacao-pura-vertical-novel-bv-financeira-en-us') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='social-media-en-us' AND type='categorias');
INSERT OR IGNORE INTO edp_posts_taxonomies (post_id, term_id)
SELECT (SELECT id FROM edp_posts WHERE slug='digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo-en-us' LIMIT 1), (SELECT id FROM edp_taxonomies WHERE slug='social-media-en-us' AND type='categorias' LIMIT 1)
WHERE EXISTS (SELECT 1 FROM edp_posts WHERE slug='digital-campaign-aberto-ao-publico-temporada-1-e-2-tvglobo-en-us') AND EXISTS (SELECT 1 FROM edp_taxonomies WHERE slug='social-media-en-us' AND type='categorias');
